### ISSUE TITLE
Add SSL Support

### ISSUE THREAD

**Issue by reynoldsalec** [lando/phpmyadmin#50]
Although there isn't a security reason per say, having SSL enabled would be a nice-to-have so users don't need to click through browser warnings.

I thought adding the following to the builder should work but it doesn't appear to:

```
options.ssl = true;
options.sslExpose = false;
```

**Comment by AaronFeledy** [comment]
This works in my landofile:
```yaml
services:
  pma:
    type: phpmyadmin
    ssl: true
    sslExpose: false
proxy:
  pma:
    - pma.mysite.lndo.site
```
