### ISSUE TITLE
Error: Access Denied

### ISSUE THREAD

**Issue by rrdgcoks** [lando/phpmyadmin#55]
Hello, I'm using Lando in a Docker Desktop/Ubuntu environment. This plugin is installed and it's firing up. I can click the link to get to the URL for phpMyAdmin. Here's the error shown on the page:

```
MySQL said: Documentation

Cannot connect: invalid settings.
 mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'172.20.0.4' (using password: NO)
 phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.
```

It's trying to use my Ubuntu user "root" apparently, even though I've configured mariadb in the docker-composer file to have different credentials.

```
mariadb:
    #image: amazeeio/mariadb-drupal
    image: uselagoon/mysql-8.0:latest
    labels:
      lagoon.type: mariadb
      lando.type: mariadb-drupal
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top
    environment:
      << : *default-environment
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
```

**Comment by rrdgcoks** [comment]
I tried doing this and restarting Lando, but it doesn't work:
```
services:
  solr:
    command: solr-precreate drupal /solr-conf
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - mariadb
    overrides:
      environment:
        PMA_HOST: drupal
        PMA_USER: drupal
        PMA_PASSWORD: drupal
```
I got this idea from here: https://docs.lando.dev/plugins/phpmyadmin/config.html.

**Comment by rrdgcoks** [comment]
Results of `lando drush sql-connect`
mysql --user=drupal --password=drupal --database=drupal --host=mariadb --port=3306 -A

**Comment by rrdgcoks** [comment]
Since adding this to the lando file, I have a different error trying to access the phpMyAdmin URL.

```
services:
  solr:
    command: solr-precreate drupal /solr-conf
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - mariadb
    overrides:
      environment:
        PMA_HOST: mariadb
        PMA_USER: drupal
        PMA_PASSWORD: drupal
```

Here are the new errors

MySQL said: Documentation

Cannot connect: invalid settings.
 mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
 mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
 phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.

**Comment by rrdgcoks** [comment]
I changed the PMA_Host like this
```
name: dgcoks
recipe: lagoon
config:
  flavor: drupal
  webroot: /web
  build:
    - composer install
  php: '8.3'
services:
  solr:
    command: solr-precreate drupal /solr-conf
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - mariadb
    overrides:
      environment:
        PMA_HOST: mariadb
        PMA_USER: drupal
        PMA_PASSWORD: drupal
        PMA_ARBITRARY: 1
```
I rebuilt Lando and it's now working. These "overrides" are what helped me.
