### ISSUE TITLE
Getting 404 error for proxy URL

### ISSUE THREAD

**Issue by SlimDeluxe** [lando/phpmyadmin#57]
I'm trying to get a static URL to PMA for the database and AFAIK one should be able to do this by having a proxy entry.

So I have the following lando config file:
```yaml
name: hello-lando
recipe: lamp
config:
  webroot: .
  database: mariadb
services:
  phpmyadmin:
    type: phpmyadmin:5.2
    hosts:
      - database
    database:
      type: mariadb
proxy:
  appserver:
    - another.lndo.site
  phpmyadmin:
    - pma.hellolando.lndo.site

```

When start the container, this is the output:
```
Here are some vitals:

 NAME      hello-lando                     
 LOCATION  /home/omer/www/sites/pmatest    
 SERVICES  appserver, database, phpmyadmin 
 URLS                                      
  ✔ APPSERVER URLS
    ✔ http://another.lndo.site/ [200]
    ✔ https://another.lndo.site/ [200]
    ✔ http://hello-lando.lndo.site/ [200]
    ✔ https://hello-lando.lndo.site/ [200]
    ✔ https://localhost:33039 [200]
    ✔ http://localhost:33038 [200]
  ✔ PHPMYADMIN URLS
    ✔ http://pma.hellolando.lndo.site/ [200]
    ✔ https://pma.hellolando.lndo.site/ [404]
    ✔ http://localhost:33037 [200]

```

Both pma URLs are throwing "404 page not found" error.
To make sure proxying works, I added the another.lndo.site line and this shows the same content as hello-lando.lndo.site.

When I start the command:
`lando logs --service phpmyadmin --follow`
I can see the hits from http://localhost:33037, but not from the proxy URLs, so I guess it's not even reaching the service?

Things I've tried:
1. Add/remove dashes from proxy URL
2. PMA version 5.1 and 5.2
3. MySQL and MariaDB
4. Laravel recipe instead of LAMP

... but I was unable to narrow it down to one thing or get a working instance.

This is running on a Fedora 41 host.
Does this work for anyone? Any ideas what could be wrong in my case?
