### ISSUE TITLE
Switch to official phpmyadmin docker image

### ISSUE THREAD

**Issue by SlimDeluxe** [lando/phpmyadmin#61]
It would appear this plugin still pulls the [phpmyadmin/phpmyadmin](https://hub.docker.com/r/phpmyadmin/phpmyadmin) image from docker. However, that one is deprecated and the [official image](https://hub.docker.com/_/phpmyadmin) is now suggested.
While both seem to be at the same version, the old one only has amd64 builds, but the new one also has arm and others. So only the new one works for arm-based Macs.

To fix this, we can override the image like this:
```
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
    database:
      type: mariadb:10.11
    overrides:
      image: phpmyadmin
```
... but I think it would be nice if you just switched the image being used in the plugin to the new one.
