### ISSUE TITLE
Drupal multisite databases not being displayed in PHPMyadmin

### ISSUE THREAD

**Issue by prashantdsala** [lando/phpmyadmin#8]

**Comment by labboy0276** [comment]
@prashantdsala Have you tried doing this:

```
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - subsite1
      - subsite2
```
